name: wolfx_dart_utils
description: Dart Utils
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.3 <3.0.0'

dependencies:
  dartx: ^1.1.0
  json_by_path: ^0.0.2-beta
  path: ^1.8.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  loggy: ^2.0.1+1
  isolate_manager: ^2.0.1